services:
  - type: web
    name: laravel-app
    env: docker
    plan: free
    branch: main
    region: oregon
    dockerContext: .
    dockerfilePath: Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        sync: false # voeg dit toe via de webinterface of secrets
      - key: APP_URL
        value: https://<jouw-render-subdomein>.onrender.com
      - key: DB_CONNECTION
        value: mysql # of pgsql
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_DATABASE
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
